### ISSUE TITLE
Alternate Box Selection methods

### ISSUE THREAD

**Issue by InkDragon** [gocario/PKBrew#1]
Would it be possible to add a way to select a box to the lower screen or set custom buttons for it?

I ask because shoulder buttons have a notoriously high failure rate, and without them it limits a user to only editing the first box.

**Comment by gocario** [comment]
PKBrew is just a data repository.
Also [PCHex++](https://github.com/Slashcash/PCHex-plusplus/issues/6)?

**Comment by InkDragon** [comment]
was meant to go on PHBankGB, sorry for any confusion
