### ISSUE TITLE
[Enhancement] VC inject GSC

### ISSUE THREAD

**Issue by Dimensional** [gocario/PKBrew#2]
Given someone managed to use the original RBY VCs to make ones for GSC with the same wireless linking function, maybe the PKBrew GC bank could be updated to include these games too, unofficially? It could be used as a means of trading between generations that are on the same system. Of course, any pokemon/items/moves only found in GSC would have to greyed out when the selected game to transfer to/from is RBY.

**Comment by gocario** [comment]
That issue belongs to PHBankGB.

**Comment by Dimensional** [comment]
Sorry. I thought I was on the repo. My mistake.
